export { FormLogin } from "./auth/Login.Form";
export { OptionsSingUp } from "./auth/OptionsSingUp";
export { FormSingUp } from "./auth/SingUp.Form";
export { FormForgetPassword } from "./auth/ForgetPassword.Form";
export { FormEvents } from "./events/Events.Form";
export { EventsOptions } from "./events/Events.options";
export { EventUploadImg } from "./events/Events.UploadImg";
export { FormPresident } from "./president/President.Form";
export { PresidentOptions } from "./president/President.options";